FROM node:18-alpine

WORKDIR /app

COPY . .

RUN yarn install --frozen-lockfile
RUN yarn cache clean

RUN yarn build

FROM node:18-alpine

WORKDIR /app

COPY --from=0 /app/package.json ./
COPY --from=0 /app/yarn.lock ./

RUN yarn install --production --frozen-lockfile
RUN yarn cache clean

COPY --from=0 /app/build ./

ENV PORT=80
EXPOSE 80
CMD ["node", "./index.js"]