version: "3.9"
services:
  frontend:
    build: frontend
    restart: always
    ports:
      - "80:80"
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "test"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
